apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-report
  namespace: app
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: be-report
  template:
    metadata:
      labels:
        app: be-report
      annotations:
        instrumentation.opentelemetry.io/inject-python: "java-instrumentation"
    spec:
      imagePullSecrets:
        - name: harbor-credentials
      containers:
        - name: be-report
          image: harbor.platform.local/app/be-report:af89bfc1
          ports:
            - containerPort: 8000
          env:
            - name: OTEL_SERVICE_NAME
              value: be-report
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: http/protobuf
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://192.168.122.175:4318
            - name: OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED
              value: "true"
            - name: REDIS_HOST
              value: redis-master
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: SUBSCRIPTION_URL
              value: http://be-subscription:8080
            - name: PRODUCT_URL
              value: http://be-product:8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 15
          resources:
            requests:
              memory: "128Mi"
              cpu: "10m"
            limits:
              memory: "256Mi"
              cpu: "300m"
