apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-bff
  namespace: app
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: be-bff
  template:
    metadata:
      labels:
        app: be-bff
      annotations:
        instrumentation.opentelemetry.io/inject-java: "java-instrumentation"
    spec:
      imagePullSecrets:
        - name: harbor-credentials
      containers:
        - name: be-bff
          image: harbor.platform.local/app/be-bff:latest
          ports:
            - containerPort: 8080
          env:
            - name: OTEL_SERVICE_NAME
              value: be-bff
            - name: SERVICES_AUTH_URL
              value: http://be-auth:8080
            - name: SERVICES_PRODUCT_URL
              value: http://be-product:8080
            - name: SERVICES_SUBSCRIPTION_URL
              value: http://be-subscription:8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
          resources:
            requests:
              memory: "256Mi"
              cpu: "10m"
            limits:
              memory: "512Mi"
              cpu: "500m"
