apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-subscription
  namespace: app
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: be-subscription
  template:
    metadata:
      labels:
        app: be-subscription
      annotations:
        instrumentation.opentelemetry.io/inject-java: "true"
    spec:
      imagePullSecrets:
        - name: harbor-credentials
      containers:
        - name: be-subscription
          image: harbor.platform.local/app/be-subscription:latest
          ports:
            - containerPort: 8080
          env:
            - name: OTEL_SERVICE_NAME
              value: be-subscription
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: SPRING_APPLICATION_JSON
              value: '{"spring":{"kafka":{"properties":{"security.protocol":"SASL_PLAINTEXT","sasl.mechanism":"PLAIN","sasl.jaas.config":"org.apache.kafka.common.security.plain.PlainLoginModule required username=\"user1\" password=\"plCxJVIBcH\";"}}}}'
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
          resources:
            requests:
              memory: "256Mi"
              cpu: "10m"
            limits:
              memory: "512Mi"
              cpu: "500m"
