apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-product
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: be-product
  template:
    metadata:
      labels:
        app: be-product
      annotations:
        instrumentation.opentelemetry.io/inject-java: "true"
    spec:
      imagePullSecrets:
        - name: harbor-credentials
      containers:
        - name: be-product
          image: harbor.platform.local/app/be-product:latest
          ports:
            - containerPort: 8080
          env:
            - name: OTEL_SERVICE_NAME
              value: be-product
            - name: REDIS_HOST
              value: redis-master
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
          resources:
            requests:
              memory: "256Mi"
              cpu: "10m"
            limits:
              memory: "512Mi"
              cpu: "500m"