apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-product
  namespace: app
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: be-product
  template:
    metadata:
      labels:
        app.kubernetes.io/name: be-product
      annotations:
        instrumentation.opentelemetry.io/inject-java: "platform-observability/java-instrumentation"
    spec:
      imagePullSecrets:
        - name: harbor-credentials
      containers:
        - name: be-product
          image: harbor.platform.local/app/be-product:5eab7b74
          ports:
            - containerPort: 8080
          env:
            - name: OTEL_INSTRUMENTATION_LOGBACK_APPENDER_EXPERIMENTAL_LOG_ATTRIBUTES
              value: "true"
            - name: OTEL_INSTRUMENTATION_LOGBACK_APPENDER_EXPERIMENTAL_CAPTURE_MDC_ATTRIBUTES
              value: "*"
            - name: OTEL_INSTRUMENTATION_LOGBACK_APPENDER_EXPERIMENTAL_CAPTURE_KEY_VALUE_PAIR_ATTRIBUTES
              value: "true"
            - name: REDIS_HOST
              value: redis-master
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: SPRING_APPLICATION_JSON
              value: '{"logging.level.net.kubeworks.beproduct.filter.OTELInstrumentationFilter": "debug", "spring":{"kafka":{"properties":{"security.protocol":"SASL_PLAINTEXT","sasl.mechanism":"PLAIN","sasl.jaas.config":"org.apache.kafka.common.security.plain.PlainLoginModule required username=\"user1\" password=\"plCxJVIBcH\";"}}}}'
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 50
            periodSeconds: 10
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 50
            periodSeconds: 15
          resources:
            requests:
              memory: "256Mi"
              cpu: "10m"
            limits:
              memory: "512Mi"
              cpu: "500m"
