apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-web-nextjs
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: fe-web-nextjs
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fe-web-nextjs
      annotations:
        instrumentation.opentelemetry.io/inject-nodejs: "platform-observability/java-instrumentation"
    spec:
      imagePullSecrets:
        - name: harbor-credentials
      containers:
        - name: fe-web-nextjs
          image: harbor.platform.local/app/fe-web-nextjs:bf7d976c
          ports:
            - containerPort: 3000
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: BFF_URL
              value: http://be-bff:8080
            - name: OTEL_LOGS_EXPORTER
              value: otlp
            - name: OTEL_COLLECTOR_HTTP_URL
              value: http://$(NODE_IP):4318
            - name: NEXT_PUBLIC_SERVICE_NAME
              value: fe-web-nextjs
            - name: HOSTNAME
              value: "0.0.0.0"
            - name: NEXT_PUBLIC_BFF_URL
              value: "http://bff.platform.local"
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 15
          resources:
            requests:
              memory: "256Mi"
              # cpu: "500m"
            limits:
              memory: "512Mi"
              # cpu: "500m"

