apiVersion: v1
kind: Service
metadata:
  name: otelcol
  namespace: platform-observability
spec:
  selector:
    app.kubernetes.io/instance: otelcol
    app.kubernetes.io/name: opentelemetry-collector
    component: agent-collector
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318